name: Health Check

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - name: Check URL
        run: curl -sSf ${{ secrets.SITE_URL }} -m 30 > /dev/null

  notify-failure:
    name: notify-failure
    runs-on: ubuntu-latest
    needs: [check]
    if: ${{ failure() }}
    steps:
      - name: Send Discord notification
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          message: "🔴 ${{ secrets.SITE_URL }} is offline"

  notify-success:
    name: notify-success
    runs-on: ubuntu-latest
    needs: [check]
    steps:
      - name: Get previous Health Check run status
        id: get_prev_status
        run: >
          echo "::set-output name=previous_status::$(
            curl -sSf 'https://api.github.com/repos/${{ github.repository }}/actions/runs' | 
            jq -r '[.workflow_runs[] | select(.name=="${{ github.workflow }}")][1].conclusion'
          )"
      - name: Send Discord notification
        if: ${{ steps.get_prev_status.outputs.previous_status != 'success' }}
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          message: "🟢 ${{ secrets.SITE_URL }} is back online"
