name: Health Check

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - run: curl -sSf ${{ secrets.SITE_URL }} > /dev/null

  notify:
    name: notify
    runs-on: ubuntu-latest
    needs: [check]
    if: ${{ failure() }}
    steps:
      - run: echo failure > status.txt
      - uses: actions/upload-artifact@v2
        with:
          name: status
          path: status.txt
      - name: Send Discord notification
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          message: "🔴 ${{ secrets.SITE_URL }} is offline"
