name: Health Check

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - name: Check URL
        run: curl -sSf ${{ secrets.SITE_URL }} -m 30 > /dev/null

  notify-failure:
    name: notify-failure
    runs-on: ubuntu-latest
    needs: [check]
    if: ${{ failure() }}
    steps:
      - name: Send Discord notification
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          message: "🔴 ${{ secrets.SITE_URL }} is offline"

  notify-success:
    name: notify-success
    runs-on: ubuntu-latest
    needs: [check]
    steps:
      - uses: octokit/request-action@v2.x
        id: get_workflows_runs
        with:
          route: GET /repos/rbarbazz/automations/actions/runs
          owner: octokit
          repo: request-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Send Discord notification
        if: fromJson(steps.get_workflows_runs.outputs.data).workflow_runs[1].conclusion != 'success'
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          message: "🟢 ${{ secrets.SITE_URL }} is back online"
