name: Keep Alive
on:
  schedule:
    - cron: '42 0 * * *'

jobs:
  keepalive:
    name: Keep Alive
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/keepalive-workflow@v1
        with:
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          committer_username: 'github-actions[bot]'
          committer_email: '41898282+github-actions[bot]@users.noreply.github.com'
